### ISSUE TITLE
Add ability to change required capability

### ISSUE THREAD

**Issue by emreerkan** [HandyPlugins/handywriter#2]
It would be nice if I can give access to settings pages to different roles. I use editor role a lot and if I can enable settings to editors with a filter [here](https://github.com/HandyPlugins/handywriter/blob/dbe1d4d54e5fc00156c34de353d81472819ed4a7/includes/admin/dashboard.php#L83) or [there](https://github.com/HandyPlugins/handywriter/blob/dbe1d4d54e5fc00156c34de353d81472819ed4a7/includes/admin/dashboard.php#L114), or even better from the settings page itself, that would be great.

An example setting section for reference:
![resim](https://github.com/HandyPlugins/handywriter/assets/529484/d7bf3ba4-3782-4040-a073-2cbb20952a83)

**Comment by mustafauysal** [comment]
@emreerkan this is an already existing feature, you can choose the minimum required capability under the settings:

![CleanShot 2023-05-18 at 10 59 24](https://github.com/HandyPlugins/handywriter/assets/1421387/a129ae21-87eb-4071-b5b5-773b0efe000a)
